Server:
  # development å¼€å‘æ¨¡å¼ production ç”Ÿäº§æ¨¡å¼
  AppMode: production
  Host: localhost
  Port: 16879
  # JwtåŠ å¯†ç§˜é’¥
  JwtKey:
  Database:
    Type: mysql
    Host: localhost
    Port: 3306
    User: root
    PassWord:
    Name: qblog
    Redis:
      Host: localhost
      Port: 6379
      Password:
      Db: 0
  Oss:
    #ossæœåŠ¡å•†ï¼Œæ”¯æŒ[qiniu,aliyun]
    Name: aliyun
    qiniu:
      AccessKey:
      SecretKey:
      Bucket:
      Sever:
    aliyun:
      AccessKeyId:
      AccessKeySecret:
      Endpoint:
      BucketName:
  Push:
    # å¯ç”¨å“ªä¸ª,ç©ºæˆ–å…¶ä»–ä¸ºä¸å¯ç”¨
    Enable: Email
    # ä¼ä¸šå¾®ä¿¡æ¨é€
    # éœ€è¦æ³¨æ„ä¼ä¸šå¾®ä¿¡ï¼Œåé¢æ–°å»ºçš„åº”ç”¨å¿…é¡»è¦ipç™½åå•ï¼Œä¸ç„¶ç”¨ä¸äº†
    WxPush:
      CorpId:
      Agentid:
      Secret:
    # é‚®ç®±
    Email:
      # å‘é€æ–¹å’Œæˆæƒç 
      From:
      Password:
      # ä¸å¡«é»˜è®¤å‘ç»™è‡ªå·±
      To:
      Host: smtp.qq.com
      Port: 25

Log:
  # æ˜¯å¦å¯ç”¨
  Enable: true
  # æ—¥å¿—ç­‰çº§ ç”Ÿäº§ç¯å¢ƒæ¨è warn
  Level: warn
  # æ—¥å¿—æ–‡ä»¶å
  Filename: log/log.log
  # æœ€å¤§å¤§å°
  MaxSize: 10
  # æœ€é•¿æ—¶é—´
  MaxAge: 28
  # æœ€å¤§å¤‡ä»½
  MaxBackups: 5
  # æ˜¯å¦å‹ç¼©
  Compress: false
SiteInfo:
  # ç½‘å€å¸¦ http,ç”¨äºç”Ÿæˆç«™ç‚¹åœ°å›¾
  Url: https://ocyss.icu
  # åšå®¢å
  Name: ğŸ’˜  Ocyss çš„åšå®¢
  # åšä¸»å
  User: Ocyss
  # é‚®ç®±åœ°å€
  Email: qiudie@88.com
  # åšå®¢æè¿°
  Desc: æ•…äº‹å¾ˆçŸ­ï¼Œæ»¡æ˜¯é—æ†¾ã€‚
  # å»ºç«™æ—¶é—´ ç§’çº§æ—¶é—´æˆ³ 2022-09-07T12:39:08+08:00
  ConstructionTime: 1662525548
